version: "3"

services:
  homeassistant:
    container_name: ha-dev
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ../../home-assistant:/config
    ports:
      - "8123:8123"
    restart: unless-stopped